title: Technology Blog - Hitendra Jagtap.
description: > # this means to ignore newlines until "baseurl:"
  An inquisitive blog on Technology.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.hiten.dev" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Hitendra Jagtap # add your name
author-img: hjagtap.jpg # add your photo
about-author: I am a passionate software developer, cloud consultant, positive change agent, and a musician. Like you, I am a good human being, trying to be better at everything I am, and everything I do. I heartily welcome you in this journey. # add description
social-twitter: hitendrajagtap # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: hitendrajagtap # add your Github handle
social-linkedin: hitendrajagtap # add your Linkedin handle
social-email: hitendra.jagtap@live.in # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
